### ISSUE TITLE
Support for internal LED on CC2531

### ISSUE THREAD

**Issue by romanpeters** [AndrewLinden/xiaomi-zb2mqtt#13]
This might not be the most pressing issue, but it would be nice if the LED on the CC2531 itself could be controlled by MQTT as well. 

I happily replaced my Xiamoi Aqara with the CC2531, but that green LED is incredibly bright for its size --illuminating my bed room at night.

Though, I have no idea if this is something that can be controlled with this hardware.

**Comment by ptvoinfo** [comment]
This is possible with a custom firmware only. I've painted over this LED by a black marker. I've also tried a women's red nail polish.

**Comment by romanpeters** [comment]
I carefully removed the LED with an x-acto knife, which resolved my problem.
